project:
  type: website
  output-dir: _site
  pre-render: "node scripts/generate_hashes.js"
  post-render: "node scripts/archive_html.js"
  resources:
    - "versions.json"

website:
  title: "Thinghood Limited"
  site-url: "https://thing.rodeo"
  search: false
  navbar:
    left:
      - text: "Home"
        href: "https://thing.rodeo/"
      - text: "Study"
        href: "https://study.thing.rodeo/"
      - text: "Logic"
        href: "https://thing.rodeo/computation-metalogic/"
      - text: "Living Syllabus"
        href: "https://thing.rodeo/living-syllabus/"
      - text: "About"
        href: "https://thing.rodeo/about/"
    right:
      - text: "Sign in"
        href: "https://thing.rodeo/#/portal/signin"
      - text: "<span class='nav-subscribe-btn'>Subscribe</span>"
        href: "https://thing.rodeo/#/portal/signup"
  sidebar:
    - id: nf-set-theory
      title: "NF Set Theory"
      contents:
        - nf-set-theory/index.qmd
        - nf-set-theory/topology-transclusion.qmd
        - nf-set-theory/quine-math-logic.qmd
        - nf-set-theory/hailperin-axioms.qmd
        - nf-set-theory/specker-orey-jensen.qmd
        - nf-set-theory/forster-holmes.qmd
        - nf-set-theory/mac-lane-lawvere.qmd
        - nf-set-theory/lambek-scott.qmd
        - nf-set-theory/mclarty-forster-stratified.qmd
    - id: computation-metalogic
      title: "Computational Metalogic"
      contents:
        - computation-metalogic/index.qmd
        - computation-metalogic/01-conceptual-foundations.qmd
        - computation-metalogic/02-syntax.qmd
        - computation-metalogic/03-deduction.qmd
        - computation-metalogic/04-semantics.qmd
        - computation-metalogic/05-translation.qmd
        - computation-metalogic/06-metalogic.qmd
        - computation-metalogic/07-conclusion.qmd

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true